# Misc options
SEED: 42

# Default Hydra Configs
defaults:
  - model: default
  - optimizer: Ranger
  - scheduler: FlatCos
  - transforms: GenericImageTransforms

DATASETS:
  TRAIN: " " # Name of registered train dataset
  VALID: " " # Name of the registered validation dataset
