# @package OPTIMIZER
NAME: RMSpropTF
ARGUMENTS:
  lr: ${SOLVER.BASE_LR}
  alpha: 0.9
  weight_decay: ${SOLVER.WEIGHT_DECAY}
  momentum: 0.0
  centered: false
  decoupled_decay: false
  lr_in_momentum: true
