# Misc options
VERSION: 1
SEED: 42

# Default Hydra Configs
defaults:
  - model: default
  - optimizer: default
  - scheduler: default
  - transforms: imagenet

DATASETS:
  TRAIN: " " # Name of registered train dataset
  VALID: " " # Name of the registered validation dataset
