# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"default_logger": "00a_utils.common.ipynb",
         "imshow_tensor": "00a_utils.common.ipynb",
         "generate_random_id": "00a_utils.common.ipynb",
         "logger": "01a_data.transforms.ipynb",
         "Urls": "00b_utils.data.ipynb",
         "download_data": "00b_utils.data.ipynb",
         "pil_loader": "00b_utils.data.ipynb",
         "cv2_loader": "00b_utils.data.ipynb",
         "folder2df": "00b_utils.data.ipynb",
         "stratify_df": "00b_utils.data.ipynb",
         "TransformCatalog": "01a_data.transforms.ipynb",
         "ImageClassificationTransforms": "01a_data.transforms.ipynb",
         "TorchvisionTransform": "01a_data.transforms.ipynb",
         "AlbumentationsTransform": "01a_data.transforms.ipynb",
         "ImagenetNoAugmentTransform": "01a_data.transforms.ipynb",
         "GenericImageTransform": "01a_data.transforms.ipynb",
         "AugTransforms": "01a_data.transforms.ipynb"}

modules = ["utils/common.py",
           "utils/data.py",
           "data/transforms.py"]

doc_url = "https://benihime91.github.io/lightning_cv/"

git_url = "https://github.com/benihime91/lightning_cv/tree/master/"

def custom_doc_links(name): return None
