# @package MODEL
BACKBONE:
  NAME: TimmCnnBody
  ARGUMENTS:
    model_name: resnet18
    cut: -2
    act_layer: null
    pretrained: true
CLASSIFIER:
  NAME: GeneralClassifier
  ARGUMENTS:
    num_features: ???
    num_classes: ???
    drop_rate: 0.25
    pool_type: avg
    use_conv: False
