# @package TRANSFORMS
TRAIN:
  LOADER: pil_loader
  NAME: GenericImageTransform
  ARGUMENTS:
    img_size: ${INPUT.SIZE_TRAIN}
    interpolation: random
    hflip: 0.5
    vflip: 0.5
    color_jitter: 0.4
    re_prob: 0.5
    re_mode: pixel
    re_count: 1
    mean: ${INPUT.MEAN_TRAIN}
    std: ${INPUT.STD_TRAIN}

VALID:
  LOADER: pil_loader
  NAME: ImagenetNoAugmentTransform
  ARGUMENTS:
    img_size: ${INPUT.SIZE_VALID}
    interpolation: bilinear
    mean: ${INPUT.MEAN_VALID}
    std: ${INPUT.STD_VALID}
