# @package TRANSFORMS
TRAIN:
  LOADER: pil_loader
  NAME: GenericImageTransform
  ARGUMENTS:
    img_size: 224
    interpolation: random
    hflip: 0.5
    vflip: 0.5
    color_jitter: 0.4
    re_prob: 0.5
    re_mode: pixel
    re_count: 1
    mean:
      - 0.485
      - 0.456
      - 0.406
    std:
      - 0.229
      - 0.224
      - 0.225

VALID:
  LOADER: pil_loader
  NAME: ImagenetNoAugmentTransform
  ARGUMENTS:
    img_size: 224
    interpolation: bilinear
    mean:
      - 0.485
      - 0.456
      - 0.406
    std:
      - 0.229
      - 0.224
      - 0.225
