# @package SCHEDULER
NAME: OneCycleLR
ARGUMENTS:
  max_lr: ${SOLVER.BASE_LR}
  epochs: null
  steps_per_epoch: null
  anneal_strategy: cos
  cycle_momentum: true
INTERVAL: step
FREQUENCY: 1
MONITOR: null
